### ISSUE TITLE
Pre-trained data?

### ISSUE THREAD

**Issue by peoplecure** [zabir-nabil/text-image-denoiser#1]
Hi, do you have pre-trained data that I can use on the fly?

**Comment by zabir-nabil** [comment]
Do you mean pre-trained model?

**Comment by peoplecure** [comment]
> Do you mean pre-trained model?

Yes, in the past, I've used to download files instead of training the data (or model) myself. The pre-trained models were incredibly helpful because I have a 2013 Macbook Air. 

I really like this study because it looks the most promising and suited for my learning topic.

**Comment by zabir-nabil** [comment]
Unfortunately, I don't remember which model gave me the best results, but I found this one on my server: https://drive.google.com/file/d/18wdob0j2xrFg8jcbRewvyqwwr7z0JNsG/view?usp=sharing

**Comment by peoplecure** [comment]
Thanks!
